name: "Test typescript-action"
on:
  pull_request:
  issue:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with:
        repo-token: ${{ secrets.TOKEN }}
        welcome-message: "Hi"
