name: "Test"
on:
  pull_request:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: "Send Review Request"
      if: github.actor == 'kunihiko-t'
      uses: ./
      with:
        repo-token: ${{ secrets.TOKEN }}
        reviewers: "valletta-io"
        team-reviewers: ""

